export const guiComponentContract = {
  GuiScrollView: {
    host: "ipp-gui-scroll-view",
    fields: {
      axis: "number",
      bar_thickness: "number",
      bar_inset: "number",
      bar_end_inset: "number",
    },
  },
  GuiVirtualList: {
    host: "ipp-gui-virtual-list",
    fields: {
      item_count: "number",
      item_extent: "number",
      overscan: "number",
      axis: "number",
      bar_thickness: "number",
      bar_inset: "number",
      bar_end_inset: "number",
    },
  },
  GuiVirtualItem: { host: "ipp-gui-virtual-item", fields: { index: "number" } },
  CanvasStyle: {
    host: "ipp-canvas-style",
    fields: {
      x: "number",
      y: "number",
      scale_x: "number",
      scale_y: "number",
      red: "number",
      green: "number",
      blue: "number",
      alpha: "number",
      opacity: "number",
      clipped: "boolean",
      clip_min_x: "number",
      clip_min_y: "number",
      clip_max_x: "number",
      clip_max_y: "number",
      layer: "number",
    },
  },
  CanvasLayerTransition: {
    host: "ipp-canvas-layer-transition",
    fields: { previous_layer: "number", progress: "number" },
  },
  CanvasText: {
    host: "ipp-canvas-text",
    fields: {
      text: "string",
      source: "string",
      variant: "number",
      font_size: "number",
    },
  },
  CanvasGlyphRun: {
    host: "ipp-canvas-glyph-run",
    fields: {
      source: "string",
      variant: "number",
      font_size: "number",
      glyphs: "bytes",
    },
  },
  CanvasDrawing: {
    host: "ipp-canvas-drawing",
    fields: { source: "string", variant: "number" },
  },
  CanvasBitmap: {
    host: "ipp-canvas-bitmap",
    fields: {
      source: "string",
      variant: "number",
      width: "number",
      height: "number",
    },
  },
  CanvasBox: {
    host: "ipp-canvas-box",
    fields: {
      width: "number",
      height: "number",
      radius_x: "number",
      radius_y: "number",
    },
  },
  CanvasPaint: {
    host: "ipp-canvas-paint",
    fields: { source: "string", variant: "number" },
  },
  GuiLayout: {
    host: "ipp-gui-layout",
    fields: {
      kind: "number",
      width: "number",
      height: "number",
      min_width: "number",
      min_height: "number",
      max_width: "number",
      max_height: "number",
      flex: "number",
      align_x: "number",
      align_y: "number",
      clip: "boolean",
      padding_top: "number",
      padding_right: "number",
      padding_bottom: "number",
      padding_left: "number",
      margin_top: "number",
      margin_right: "number",
      margin_bottom: "number",
      margin_left: "number",
    },
  },
  GuiOverlay: {
    host: "ipp-gui-overlay",
    fields: { side: "number", align: "number", mode: "number", band: "number" },
  },
  GuiGroup: {
    host: "ipp-gui-group",
    fields: { axis: "number", selection: "number" },
  },
  GuiBehavior: {
    host: "ipp-gui-behavior",
    fields: {
      enabled: "boolean",
      visible: "boolean",
      focus_scope: "boolean",
      focusable: "boolean",
      semantic_label: "string",
    },
  },
  GuiFont: {
    host: "ipp-gui-font",
    fields: { source: "string", variant: "number", font_size: "number" },
  },
  GuiTheme: { host: "ipp-gui-theme", fields: { parts: "bytes", em: "number" } },
  GuiThemeMotion: {
    host: "ipp-gui-theme-motion",
    fields: { parts: "bytes" },
  },
  GuiSkin: {
    host: "ipp-gui-skin",
    fields: { theme: "entity", parts: "bytes" },
  },
  GuiButton: {
    host: "ipp-gui-button",
    fields: { label: "string", selected: "boolean" },
  },
  GuiCheckbox: {
    host: "ipp-gui-checkbox",
    fields: { label: "string", checked: "boolean" },
  },
  GuiSlider: {
    host: "ipp-gui-slider",
    fields: {
      min: "number",
      max: "number",
      step: "number",
      fine_step: "number",
      value: "number",
      origin: "number",
      axis: "number",
      range: "boolean",
      upper: "number",
    },
  },
  GuiTextInput: {
    host: "ipp-gui-text-input",
    fields: {
      placeholder: "string",
      text: "string",
      masked: "boolean",
      numeric: "boolean",
      value: "number",
      min: "number",
      max: "number",
      step: "number",
      fine_step: "number",
      precision: "number",
      step_parts: "boolean",
    },
  },
  GuiColor: {
    host: "ipp-gui-color",
    fields: {
      hue: "number",
      saturation: "number",
      value: "number",
      alpha: "number",
      alpha_rail: "boolean",
    },
  },
} as const;

export const guiControlNames = new Set([
  "GuiScrollView",
  "GuiVirtualList",
  "GuiButton",
  "GuiCheckbox",
  "GuiSlider",
  "GuiTextInput",
  "GuiColor",
]);
