/** Cooperative publication protocol for generated external shared bytes.
 * These buffers are copied once into reader-owned WASM storage; they are not
 * addressable WASM linear memory. Direct borrowing from shared WebAssembly.Memory
 * is not implemented by this adapter. The producer must honor the guard and avoid
 * writes through other views until release; JavaScript cannot enforce readonly
 * shared bytes against arbitrary code outside this cooperative protocol.
 */
export interface SharedBufferPublication {
  readonly buffer: SharedArrayBuffer;
  readonly control: SharedArrayBuffer;
  readonly generation: number;
  readonly offset: number;
  readonly length: number;
}

/** Own generated bytes, publish an immutable incarnation, then await its release. */
export class SharedBufferProducer {
  private readonly buffer: SharedArrayBuffer;
  private readonly control = new SharedArrayBuffer(8);

  constructor(length: number) {
    if (!Number.isSafeInteger(length) || length < 0)
      throw new RangeError("Invalid shared source length");
    this.buffer = new SharedArrayBuffer(length);
  }

  /** The callback must not retain its mutable view or write outside this lease. */
  publish(
    write: (bytes: Uint8Array<SharedArrayBuffer>) => void,
  ): SharedBufferPublication {
    const state = new Int32Array(this.control);
    if (Atomics.compareExchange(state, 0, 0, 1) !== 0)
      throw new Error("Previous shared source publication is still retained");
    const previous = Atomics.load(state, 1);
    if (previous < 0 || previous >= 0x7fffffff) {
      Atomics.store(state, 0, 0);
      throw new Error("Shared publication identities exhausted");
    }
    const generation = previous + 1;
    Atomics.store(state, 1, generation);
    try {
      write(new Uint8Array(this.buffer));
      Atomics.store(state, 0, 2);
      return {
        buffer: this.buffer,
        control: this.control,
        generation,
        offset: 0,
        length: this.buffer.byteLength,
      };
    } catch (error) {
      Atomics.store(state, 0, 0);
      throw error;
    }
  }

  get released(): boolean {
    return Atomics.load(new Int32Array(this.control), 0) === 0;
  }
}

export interface WorkerBufferSource {
  /** Exact immutable source registration; use it in ordinary asset references. */
  readonly source: string;
  /** Revoke future reads, cancel acquisition, then release producer storage. */
  release(): Promise<void>;
}
