[package]
name = "ipp-wasm"
description = "IPP browser worker host"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ipp-core.workspace = true
ipp-host-session.workspace = true
ipp-protocol.workspace = true
ipp-render-gl = { workspace = true, optional = true }

[features]
default = []
instrumentation = [
    "ipp-core/instrumentation",
    "ipp-protocol/instrumentation",
    "ipp-host-session/instrumentation",
    "ipp-render-gl?/instrumentation",
]
render = ["dep:ipp-render-gl"]

[lints]
workspace = true
