/** Versioned logical workload of the React GUI stress benchmark. */
export const GUI_STRESS_WORKLOAD = {
  version: 2,
  diagnosticPanelEntities: [51, 136, 1001],
  rawSurfaceCache: {
    direct_distance: 0,
    texels_per_metre: 128,
    max_refresh_hz: 240,
  },
  seed: 0x19770517,
  viewport: { width: 1280, height: 800, dpr: 1 },
  camera: { projection: "orthographic", height: 9.4 },
  layout: {
    panelWidth: 2.2,
    panelHeight: 1.55,
    stepX: 2.42,
    stepY: 2.03,
    rawYOffset: -0.9,
    rawHeight: 0.18,
  },
  virtualItemsPerPanel: 10_000,
  virtualScrollStart: 5000,
  virtualScrollStride: 120,
  warmupFrames: 12,
  samplesPerSweep: 6,
  idleProfileFrames: 24,
  probeSweep: { name: "tree-32", panels: 4, treeRows: 32 },
  allocationActions: [
    "local-text",
    "layout",
    "theme",
    "churn",
    "control-press",
    "control-toggle",
    "control-drag",
    "virtual-scroll",
    "camera-only",
    "animation",
    "cache-idle",
  ],
  sweeps: [
    { name: "panels-1", panels: 1, treeRows: 16 },
    { name: "panels-4", panels: 4, treeRows: 16 },
    { name: "panels-9", panels: 9, treeRows: 16 },
    { name: "panels-16", panels: 16, treeRows: 16 },
    { name: "tree-8", panels: 4, treeRows: 8 },
    { name: "tree-32", panels: 4, treeRows: 32 },
    { name: "tree-64", panels: 4, treeRows: 64 },
    { name: "tree-128", panels: 4, treeRows: 128 },
  ],
  actions: [
    "idle",
    "local-text",
    "layout",
    "theme",
    "callback-only",
    "control-press",
    "control-toggle",
    "control-drag",
    "virtual-scroll",
    "camera-only",
    "animation",
    "cache-idle",
    "churn",
  ],
} as const;

export type GuiStressSweep = (typeof GUI_STRESS_WORKLOAD.sweeps)[number];
export type GuiStressAction = (typeof GUI_STRESS_WORKLOAD.actions)[number];
