use std::fmt::Write as _;

use crate::codec_limits;
use crate::export_reader::ROWS_KIND;
use crate::model::{Export, RowsLayout};
use crate::typescript_names::{identifier, js_string};

/// Maintained client source appended after the generated contract, in output order:
/// the templates and the re-export of the maintained surface configuration module.
/// Generated identifiers avoid every binding these and [`GUI_PAINT_TEMPLATE`] declare.
pub(super) const TEMPLATES: [&str; 9] = [
    include_str!("templates/codec.template.ts"),
    include_str!("templates/dataset.template.ts"),
    include_str!("templates/data-authoring.template.ts"),
    include_str!("templates/animation.template.ts"),
    include_str!("templates/geometry.template.ts"),
    include_str!("templates/gui.template.ts"),
    "\nexport * from \"./surface-config.js\";\n",
    include_str!("templates/skeleton.template.ts"),
    include_str!("templates/skinning.template.ts"),
];

/// GUI paint helpers, appended after the generated paint keys and skin looks.
pub(super) const GUI_PAINT_TEMPLATE: &str = include_str!("templates/gui-paint.template.ts");

pub(super) fn render(export: Export) -> Result<String, String> {
    let Export {
        expected,
        arch,
        os,
        pointer,
        components,
        paint_keys,
        skin_looks,
        skin_tokens,
        row_limits,
        wire,
    } = export;
    let revision = crate::WIRE_REVISION;

    let mut out = String::from(
        "// Generated by ipp-schema-gen from an executed target contract. Do not edit.\n\
function freezeContract<T>(value: T): T {\n\
  if (value !== null && typeof value === 'object' && !Object.isFrozen(value)) {\n\
    for (const nested of Object.values(value as Record<string, unknown>)) freezeContract(nested);\n\
    Object.freeze(value);\n\
  }\n\
  return value;\n\
}\n",
    );
    writeln!(
        out,
        "export const SCHEMA_HASH = {expected}n;\nexport const PROTOCOL_VERSION = {revision};\nexport const TARGET = freezeContract({{ arch: {}, os: {}, pointerBits: {pointer} }} as const);",
        js_string(&arch),
        js_string(&os),
    )
    .unwrap();
    writeln!(out, "export const WIRE = freezeContract({{").unwrap();
    for tag in &wire.tags {
        writeln!(out, "  {}: {},", tag.name, tag.value).unwrap();
    }
    for format in &wire.asset_formats {
        writeln!(out, "  {}: {},", format.name, format.type_id).unwrap();
    }
    out.push_str("} as const);\n");

    crate::paint_keys::render(&mut out, &paint_keys, &skin_looks, &skin_tokens);
    out.push_str("export const components = freezeContract({\n");

    for c in &components {
        writeln!(
            out,
            "  {}: {{ id: {}, size: {}, alignment: {}, creatable: {}, dynamicProperties: {}, fields: {{",
            c.name, c.id, c.size, c.align, c.creatable, c.dynamic_properties
        )
        .unwrap();
        for f in &c.fields {
            write!(
                out,
                "    {}: {{ offset: {}, size: {}, alignment: {}, kind: {}, default: {}",
                f.name, f.offset, f.field_size, f.field_align, f.kind, f.default
            )
            .unwrap();
            if let Some(rows) = &f.rows {
                write!(
                    out,
                    ", rows: {{ regionBase: {}, properties: [",
                    rows.region_base
                )
                .unwrap();
                for property in &rows.properties {
                    write!(
                        out,
                        " {{ name: {}, kind: {}, optional: {}, hint: {}",
                        js_string(&property.name),
                        js_string(row_property_kind(property.kind)),
                        property.optional,
                        js_string(if property.rotation {
                            "rotation"
                        } else {
                            "none"
                        }),
                    )
                    .unwrap();
                    if let Some(max_bytes) = property.max_bytes {
                        write!(out, ", maxBytes: {max_bytes}").unwrap();
                    }
                    out.push_str(" },");
                }
                out.push_str(" ] }");
            }
            out.push_str(" },\n");
        }
        out.push_str("  } },\n");
    }
    out.push_str("} as const);\n");

    let authoring = wire
        .conventions
        .iter()
        .find(|(name, _)| name == "data-authoring")
        .ok_or("target contract omits data authoring metadata")?;
    writeln!(
        out,
        "const DATA_AUTHORING = freezeContract({} as const);",
        authoring.1
    )
    .unwrap();
    codec_limits::render(&mut out, &wire, &row_limits)?;
    for template in TEMPLATES {
        out.push_str(template);
    }

    for c in &components {
        for f in &c.fields {
            if let Some(rows) = &f.rows {
                render_row_types(&mut out, &c.name, &f.name, rows)?;
            }
        }
    }

    for c in &components {
        // Only implemented command kinds receive mutation helpers.
        if c.fields
            .iter()
            .any(|f| ![1, 2, 3, 4, 5, 6, 7, ROWS_KIND, 12, 13].contains(&f.kind))
        {
            continue;
        }

        // Row tables are addressed per property, not replaced by generic helpers.
        let scalar_fields: Vec<_> = c.fields.iter().filter(|f| f.rows.is_none()).collect();
        writeln!(out, "\nexport const {} = {{", c.name).unwrap();
        writeln!(out, "  ...components.{},", c.name).unwrap();
        if c.creatable {
            // A component of only row tables takes no scalar insert values.
            let values = if scalar_fields.is_empty() {
                "_values"
            } else {
                "values"
            };
            write!(out, "  insert(entity: EntityRef, {values}: {{ ").unwrap();
            for f in &scalar_fields {
                write!(out, "{}?: {}; ", f.name, field_type(f.kind)).unwrap();
            }
            writeln!(
                out,
                "}} = {{}}): Command {{\n    const fields: FieldWrite[] = [];"
            )
            .unwrap();
            for f in &scalar_fields {
                writeln!(
                out,
                "    if (values.{} !== undefined) fields.push({{ offset: components.{}.fields.{}.offset, value: {{ kind: {}, value: values.{} }} }});",
                f.name,
                c.name,
                f.name,
                js_string(field_kind(f.kind)),
                f.name,
            )
            .unwrap();
            }
            writeln!(
            out,
            "    return {{ kind: 'insertComponent', entity, component: components.{}.id, fields }};\n  }},",
            c.name,
        )
        .unwrap();
        }
        for f in &scalar_fields {
            let title = title_case(&f.name);
            writeln!(
                out,
                "  set{title}(entity: EntityRef, value: {}): Command {{ return {{ kind: 'setField', entity, component: components.{}.id, field: {{ offset: components.{}.fields.{}.offset, value: {{ kind: {}, value }} }} }}; }},",
                field_type(f.kind),
                c.name,
                c.name,
                f.name,
                js_string(field_kind(f.kind)),
            )
            .unwrap();
        }
        for f in c.fields.iter().filter(|f| f.rows.is_some()) {
            let title = title_case(&f.name);
            let row = format!("{}{title}Row", c.name);
            let (component, field) = (&c.name, &f.name);
            writeln!(
                out,
                "  {field}Offset(slot: number, property: keyof {row}): number {{ return rowFieldOffset(components.{component}, {name}, slot, property); }},\n  \
                 patch{title}(entity: EntityRef, slot: number, patch: {row}Patch): Command[] {{ return rowPatchCommands(entity, components.{component}, {name}, slot, patch); }},\n  \
                 patch{title}Fields(slot: number, patch: {row}Patch): FieldWrite[] {{ return rowPatchFields(components.{component}, {name}, slot, patch); }},\n  \
                 encode{title}(table: RowsInput<{row}>): Uint8Array<ArrayBuffer> {{ return encodeRowsTable(components.{component}.fields.{field}.rows, table); }},\n  \
                 decode{title}(table: Uint8Array): RowsTable<{row}> {{ return decodeRowsTable<{row}>(components.{component}.fields.{field}.rows, table); }},",
                name = js_string(field),
            )
            .unwrap();
        }
        out.push_str("};\n");
    }

    Ok(out)
}

/// Emit the typed row interface and its patch type for one rows field.
fn render_row_types(
    out: &mut String,
    component: &str,
    field: &str,
    rows: &RowsLayout,
) -> Result<(), String> {
    let row = format!("{component}{}Row", title_case(field));
    identifier(&row)?;
    identifier(&format!("{row}Patch"))?;

    writeln!(
        out,
        "\n/** One `{component}.{field}` schema row; optional properties may be absent. */"
    )
    .unwrap();
    writeln!(out, "export interface {row} {{").unwrap();
    for property in &rows.properties {
        let optional = if property.optional {
            "?"
        } else {
            ""
        };
        writeln!(
            out,
            "  {}{optional}: {};",
            property.name,
            row_value_type(property.kind)
        )
        .unwrap();
    }
    out.push_str("}\n");

    writeln!(
        out,
        "/** Sparse `{component}.{field}` row write; `null` clears an optional property. */"
    )
    .unwrap();
    writeln!(out, "export interface {row}Patch {{").unwrap();
    for property in &rows.properties {
        let clear = if property.optional {
            " | null"
        } else {
            ""
        };
        writeln!(
            out,
            "  {}?: {}{clear};",
            property.name,
            row_value_type(property.kind)
        )
        .unwrap();
    }
    out.push_str("}\n");
    Ok(())
}

/// Generated helper names uppercase only a field's first letter, as setters always have.
fn title_case(name: &str) -> String {
    let mut title = name.to_owned();
    title[0..1].make_ascii_uppercase();
    title
}

fn row_property_kind(kind: u8) -> &'static str {
    match kind {
        1 => "f32",
        2 => "i32",
        3 => "u32",
        4 => "bool",
        5 => "vec2",
        6 => "vec3",
        7 => "vec4",
        12 => "asset",
        13 => "text",
        _ => unreachable!("export reader accepts only row property kinds"),
    }
}

fn row_value_type(kind: u8) -> &'static str {
    match kind {
        1..=3 => "number",
        4 => "boolean",
        5 => "readonly [number, number]",
        6 => "readonly [number, number, number]",
        7 => "readonly [number, number, number, number]",
        12 => "RowAssetValue",
        13 => "string",
        _ => unreachable!("export reader accepts only row property kinds"),
    }
}

fn field_type(kind: u8) -> &'static str {
    match kind {
        1 | 3 => "number",
        2 => "EntityRef",
        4 => "bigint",
        5 => "string",
        6 => "Uint8Array<ArrayBuffer>",
        7 => "boolean",
        12 => "WorldReference | null",
        13 => "OutputReference | null",
        _ => unreachable!("mutation helpers require supported field kinds"),
    }
}

fn field_kind(kind: u8) -> &'static str {
    match kind {
        1 => "f32",
        2 => "entity",
        3 => "u32",
        4 => "u64",
        5 => "string",
        6 => "bytes",
        7 => "bool",
        12 => "world",
        13 => "output",
        _ => unreachable!("mutation helpers require supported field kinds"),
    }
}
