//! Descriptive wire manifest module imported only by tests and tools.

use std::fmt::Write as _;

use crate::model::Export;
use crate::typescript_names::js_string;
use crate::wire_contract;

/// Render every exported convention, layout, tag layout and asset format.
///
/// Shipped clients never import this module; the codec reads the bounds it
/// needs from constants resolved into the generated client.
pub(super) fn render(export: &Export) -> String {
    let wire = &export.wire;
    let mut out = String::from(
        "// Generated by ipp-schema-gen from an executed target contract. Do not edit.\n\
// Descriptive wire manifest for tests and tools; shipped clients do not import it.\n\
function freezeContract<T>(value: T): T {\n\
  if (value !== null && typeof value === 'object' && !Object.isFrozen(value)) {\n\
    for (const nested of Object.values(value as Record<string, unknown>)) freezeContract(nested);\n\
    Object.freeze(value);\n\
  }\n\
  return value;\n\
}\n",
    );
    writeln!(out, "export const SCHEMA_HASH = {}n;", export.expected).unwrap();

    out.push_str("export const WIRE_TAG_LAYOUTS = freezeContract({\n");
    for tag in &wire.tags {
        writeln!(
            out,
            "  {}: {{ space: {}, capability: {}, layout: {} }},",
            tag.name,
            tag.space,
            js_string(wire_contract::capability_name(tag.capability).unwrap()),
            js_string(&tag.layout),
        )
        .unwrap();
    }
    out.push_str("} as const);\n");

    out.push_str("export const WIRE_CONVENTIONS = freezeContract({\n");
    for (name, value) in &wire.conventions {
        writeln!(out, "  {}: {},", js_string(name), js_string(value)).unwrap();
    }
    out.push_str("} as const);\n");

    out.push_str("export const WIRE_LAYOUTS = freezeContract({\n");
    for layout in &wire.layouts {
        writeln!(
            out,
            "  {}: {{ capability: {}, fields: [",
            js_string(&layout.name),
            js_string(wire_contract::capability_name(layout.capability).unwrap()),
        )
        .unwrap();
        for field in &layout.fields {
            writeln!(
                out,
                "    {{ name: {}, encoding: {}, limit: {}, target: {} }},",
                js_string(&field.name),
                js_string(field.encoding.name()),
                field.limit,
                js_string(&field.target),
            )
            .unwrap();
        }
        out.push_str("  ] },\n");
    }
    out.push_str("} as const);\n");

    out.push_str("export const ASSET_FORMATS = freezeContract({\n");
    for format in &wire.asset_formats {
        writeln!(
            out,
            "  {}: {{ capability: {}, typeId: {}, format: {} }},",
            format.name,
            js_string(wire_contract::capability_name(format.capability).unwrap()),
            format.type_id,
            js_string(&format.format),
        )
        .unwrap();
    }
    out.push_str("} as const);\n");
    out
}
