/** Authored Plot fields; target layouts are resolved by the React root. */
export const plotComponentContract = {
  PlotFrame2d: {
    host: "ipp-plot-frame2d",
    fields: {
      width: "number",
      height: "number",
      padding_left: "number",
      padding_top: "number",
      padding_right: "number",
      padding_bottom: "number",
      min_x: "number",
      min_y: "number",
      max_x: "number",
      max_y: "number",
      automatic_x: "boolean",
      automatic_y: "boolean",
      ticks: "number",
      x_title: "string",
      y_title: "string",
      source: "string",
      variant: "number",
      font_size: "number",
      red: "number",
      green: "number",
      blue: "number",
      alpha: "number",
      grid_red: "number",
      grid_green: "number",
      grid_blue: "number",
      grid_alpha: "number",
      line_width: "number",
    },
  },
  PlotFrame3d: {
    host: "ipp-plot-frame3d",
    fields: {
      width: "number",
      height: "number",
      depth: "number",
      min_x: "number",
      min_y: "number",
      min_z: "number",
      max_x: "number",
      max_y: "number",
      max_z: "number",
      automatic_x: "boolean",
      automatic_y: "boolean",
      automatic_z: "boolean",
      ticks: "number",
      x_title: "string",
      y_title: "string",
      z_title: "string",
      source: "string",
      variant: "number",
      font_size: "number",
      red: "number",
      green: "number",
      blue: "number",
      alpha: "number",
      grid_red: "number",
      grid_green: "number",
      grid_blue: "number",
      grid_alpha: "number",
      line_width: "number",
    },
  },
  PlotLine2d: {
    host: "ipp-plot-line2d",
    fields: {
      series: "bytes",
      labels: "bytes",
      interpolation: "number",
      line_width: "number",
      marker_size: "number",
    },
  },
  PlotBars2d: {
    host: "ipp-plot-bars2d",
    fields: {
      series: "bytes",
      labels: "bytes",
      gap: "number",
    },
  },
  PlotPie2d: {
    host: "ipp-plot-pie2d",
    fields: {
      series: "bytes",
      labels: "bytes",
      start_angle: "number",
      inner_radius: "number",
    },
  },
  PlotGridBars3d: {
    host: "ipp-plot-grid-bars3d",
    fields: {
      series: "bytes",
      labels: "bytes",
      bar_width: "number",
      bar_depth: "number",
    },
  },
  PlotHeightSurface3d: {
    host: "ipp-plot-height-surface3d",
    fields: {
      series: "bytes",
      labels: "bytes",
      wireframe: "boolean",
      line_width: "number",
    },
  },
  PlotPoints3d: {
    host: "ipp-plot-points3d",
    fields: {
      series: "bytes",
      labels: "bytes",
      marker_size: "number",
      marker_shape: "number",
    },
  },
  PlotPie3d: {
    host: "ipp-plot-pie3d",
    fields: {
      series: "bytes",
      labels: "bytes",
      start_angle: "number",
      radius: "number",
      height: "number",
    },
  },
} as const;
